FROM node:14-alpine3.11                                                                                                 
RUN apk update && apk add --no-cache git
#RUN apt update -y && apt install git -y
WORKDIR /home/node/app                                                                                                  
EXPOSE 3000 
